packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  sharp: true
  msgpackr-extract: true
  workerd: true
  lefthook: true
catalog:
  dotenv: ^17.4.2
  zod: ^4.4.3
  typescript: ^6.0.3
  "@types/node": ^22.20.1
  "@neondatabase/serverless": ^1.1.0
  elysia: ^1.4.29
  "@orpc/server": ^1.14.12
  "@orpc/openapi": ^1.14.12
  "@orpc/zod": ^1.14.12
  better-auth: 1.6.27
  "@orpc/client": ^1.14.12
